import { CrudResourceSchema } from "@/lib/types/crud";

export const CRUD_RESOURCES: CrudResourceSchema[] = [
  {
    resource: "usuarios",
    tableName: "core.usuarios",
    idKeys: ["id"],
    columns: ["id", "email", "nombre", "activo", "created_at", "updated_at"],
    requiredOnCreate: ["email", "nombre"],
    descripcion: "Usuarios de negocio",
    payloadTemplate: { email: "usuario@demo.com", nombre: "Usuario Demo", activo: true },
  },
  {
    resource: "empresas",
    tableName: "core.empresas",
    idKeys: ["id"],
    columns: ["id", "nombre", "nit", "telefono", "departamento", "ciudad", "direccion", "timezone", "activa", "created_at", "updated_at"],
    requiredOnCreate: ["nombre"],
    descripcion: "Empresas habilitadas para suscripcion",
    payloadTemplate: {
      nombre: "Empresa Demo",
      nit: "900900900-1",
      telefono: "3001234567",
      departamento: "Cundinamarca",
      ciudad: "Bogota",
      direccion: "Calle 123 #45-67",
      timezone: "UTC",
      activa: true,
    },
  },
  {
    resource: "usuarios-empresas",
    tableName: "core.usuarios_empresas",
    idKeys: ["usuario_id", "empresa_id"],
    columns: ["usuario_id", "empresa_id", "rol", "es_principal", "created_at", "updated_at"],
    requiredOnCreate: ["usuario_id", "empresa_id"],
    descripcion: "Relacion usuario-empresa",
    payloadTemplate: { usuario_id: "REEMPLAZAR-UUID", empresa_id: "REEMPLAZAR-UUID", rol: "OWNER", es_principal: true },
  },
  {
    resource: "productos",
    tableName: "billing.productos",
    idKeys: ["id"],
    columns: ["id", "codigo", "nombre", "descripcion", "tipo", "alcance", "es_consumible", "visibility", "activo", "created_at", "updated_at"],
    requiredOnCreate: ["codigo", "nombre", "tipo", "alcance", "visibility"],
    descripcion: "Catalogo de productos",
    payloadTemplate: {
      codigo: "PROD-DEMO",
      nombre: "Producto Demo",
      tipo: "SERVICIO",
      alcance: "EMPRESA",
      es_consumible: false,
      visibility: "PRIVATE",
      activo: true,
    },
  },
  {
    resource: "planes",
    tableName: "billing.planes",
    idKeys: ["id"],
    columns: ["id", "codigo", "nombre", "descripcion", "periodo", "activo", "created_at", "updated_at"],
    requiredOnCreate: ["codigo", "nombre", "periodo"],
    descripcion: "Planes comerciales",
    payloadTemplate: { codigo: "PLAN-DEMO", nombre: "Plan Demo", periodo: "MENSUAL", activo: true },
  },
  {
    resource: "precios-planes",
    tableName: "billing.precios_planes",
    idKeys: ["id"],
    columns: ["id", "plan_id", "moneda_id", "periodo", "valor", "activo", "valido_desde", "valido_hasta", "created_at", "updated_at"],
    requiredOnCreate: ["plan_id", "moneda_id", "periodo", "valor"],
    descripcion: "Precios vigentes por plan",
    payloadTemplate: { plan_id: "REEMPLAZAR-UUID", moneda_id: "REEMPLAZAR-UUID", periodo: "MENSUAL", valor: "180000", activo: true, valido_desde: "2026-02-23" },
  },
  {
    resource: "suscripciones",
    tableName: "billing.suscripciones",
    idKeys: ["id"],
    columns: ["id", "empresa_id", "plan_id", "precio_plan_id", "estado", "periodo", "modo_renovacion", "fecha_inicio", "periodo_actual_inicio", "periodo_actual_fin", "grace_days_granted", "grace_until", "operational_status", "canceled_at", "created_at", "updated_at"],
    requiredOnCreate: ["empresa_id", "plan_id", "precio_plan_id", "estado", "periodo", "modo_renovacion", "fecha_inicio", "periodo_actual_inicio", "periodo_actual_fin"],
    descripcion: "Suscripciones por empresa",
    payloadTemplate: {
      empresa_id: "REEMPLAZAR-UUID",
      plan_id: "REEMPLAZAR-UUID",
      precio_plan_id: "REEMPLAZAR-UUID",
      estado: "ACTIVA",
      periodo: "MENSUAL",
      modo_renovacion: "MANUAL",
      fecha_inicio: "2026-02-23",
      periodo_actual_inicio: "2026-02-23",
      periodo_actual_fin: "2026-03-23",
      operational_status: "EN_SERVICIO",
      grace_days_granted: 0,
      grace_until: null,
    },
  },
  {
    resource: "contratos",
    tableName: "billing.contratos",
    idKeys: ["id"],
    columns: [
      "id",
      "empresa_id",
      "plan_id",
      "billing_cycle",
      "tipo_contrato",
      "nombre_cliente_empresa",
      "nit",
      "nit_indicativo",
      "plan_nombre",
      "precio",
      "fecha_contrato",
      "fecha_primer_pago",
      "adicionales",
      "activo",
      "representante_nombre",
      "created_at",
      "updated_at",
    ],
    requiredOnCreate: [
      "billing_cycle",
      "tipo_contrato",
      "nombre_cliente_empresa",
      "nit",
      "plan_nombre",
      "precio",
      "fecha_contrato",
      "fecha_primer_pago",
      "activo",
    ],
    descripcion: "Contratos comerciales por empresa",
    payloadTemplate: {
      empresa_id: null,
      plan_id: null,
      billing_cycle: "MENSUAL",
      tipo_contrato: "mensual",
      nombre_cliente_empresa: "Cliente Demo",
      nit: "900900900",
      nit_indicativo: "1",
      plan_nombre: "Plan Lite",
      precio: "180000",
      fecha_contrato: "2026-03-18",
      fecha_primer_pago: "2026-03-18",
      adicionales: "",
      activo: true,
      representante_nombre: "Cliente Demo",
    },
  },
  {
    resource: "politicas-cobro",
    tableName: "billing.politicas_cobro",
    idKeys: ["id"],
    columns: ["id", "scope", "plan_id", "empresa_id", "grace_days", "auto_block", "activo", "created_at", "updated_at"],
    requiredOnCreate: ["scope"],
    descripcion: "Politicas de prorroga y bloqueo por mora",
    payloadTemplate: { scope: "GLOBAL", grace_days: 5, auto_block: true, activo: true },
  },
  {
    resource: "cobro-eventos",
    tableName: "billing.cobro_eventos",
    idKeys: ["id"],
    columns: ["id", "suscripcion_id", "factura_id", "event_type", "event_time", "actor", "payload_json", "created_at"],
    requiredOnCreate: ["suscripcion_id", "event_type"],
    descripcion: "Auditoria de eventos de prorroga y bloqueo",
    payloadTemplate: { suscripcion_id: "REEMPLAZAR-UUID", event_type: "GRACE_GRANTED", actor: "sistema", payload_json: { grace_until: "2026-03-31" } },
  },
  {
    resource: "items-suscripcion",
    tableName: "billing.items_suscripcion",
    idKeys: ["id"],
    columns: ["id", "suscripcion_id", "producto_id", "precio_id", "cantidad", "fecha_inicio", "fecha_fin", "fecha_efectiva_inicio", "fecha_efectiva_fin", "origen", "estado", "created_at", "updated_at"],
    requiredOnCreate: ["suscripcion_id", "producto_id", "cantidad", "fecha_inicio", "origen", "estado"],
    descripcion: "Items activos por suscripcion",
    payloadTemplate: { suscripcion_id: "REEMPLAZAR-UUID", producto_id: "REEMPLAZAR-UUID", cantidad: 1, fecha_inicio: "2026-02-23", origen: "ADDON", estado: "ACTIVO" },
  },
  {
    resource: "entitlements",
    tableName: "billing.entitlements",
    idKeys: ["id"],
    columns: ["id", "codigo", "nombre", "tipo", "alcance", "descripcion", "created_at", "updated_at"],
    requiredOnCreate: ["codigo", "nombre", "tipo", "alcance"],
    descripcion: "Capacidades y limites de negocio",
    payloadTemplate: { codigo: "LIMITE-DEMO", nombre: "Limite Demo", tipo: "LIMITE", alcance: "EMPRESA" },
  },
  {
    resource: "entitlements-suscripcion",
    tableName: "billing.entitlements_suscripcion",
    idKeys: ["suscripcion_id", "entitlement_id", "efectivo_desde"],
    columns: ["suscripcion_id", "entitlement_id", "valor_entero", "valor_booleano", "origen", "efectivo_desde", "efectivo_hasta"],
    requiredOnCreate: ["suscripcion_id", "entitlement_id", "origen", "efectivo_desde"],
    descripcion: "Valores efectivos de entitlement por suscripcion",
    payloadTemplate: { suscripcion_id: "REEMPLAZAR-UUID", entitlement_id: "REEMPLAZAR-UUID", valor_entero: 10, origen: "ADDON", efectivo_desde: "2026-02-23" },
  },
  {
    resource: "facturas",
    tableName: "billing.facturas",
    idKeys: ["id"],
    columns: ["id", "empresa_id", "suscripcion_id", "usuario_id", "fecha_emision", "fecha_vencimiento", "subtotal", "descuento_tipo", "descuento_valor", "descuento_monto", "descuento_motivo", "total", "estado", "metodo_pago", "referencia_externa", "notas", "created_at", "updated_at"],
    requiredOnCreate: ["empresa_id", "fecha_emision", "total", "estado", "metodo_pago"],
    descripcion: "Facturacion emitida",
    payloadTemplate: { empresa_id: "REEMPLAZAR-UUID", fecha_emision: "2026-02-23", subtotal: "100000", descuento_tipo: null, descuento_valor: null, descuento_monto: "0", descuento_motivo: null, total: "100000", estado: "EMITIDA", metodo_pago: "MANUAL" },
  },
  {
    resource: "prorrateos",
    tableName: "billing.prorrateos",
    idKeys: ["id"],
    columns: ["id", "suscripcion_id", "producto_id", "desde", "hasta", "valor_original", "valor_prorrateado", "factura_id", "item_factura_id", "created_at"],
    requiredOnCreate: ["suscripcion_id", "producto_id", "desde", "hasta", "valor_original", "valor_prorrateado"],
    descripcion: "Ajustes prorrateados",
    payloadTemplate: { suscripcion_id: "REEMPLAZAR-UUID", producto_id: "REEMPLAZAR-UUID", desde: "2026-02-23", hasta: "2026-03-23", valor_original: "100000", valor_prorrateado: "33333" },
  },
];

export const CRUD_RESOURCE_MAP = new Map(CRUD_RESOURCES.map((r) => [r.resource, r]));
