import { WorkflowDefinition } from "@/lib/types/workflows";

export const WORKFLOW_CATALOG: WorkflowDefinition[] = [
  {
    id: "onboard-legacy-support",
    caso: 1,
    titulo: "Cliente legacy compra soporte anual",
    descripcion: "Da de alta cliente no registrado y emite soporte anual.",
    camposMinimos: ["email", "nombre", "empresaNombre"],
    payloadTemplate: {
      email: "legacy@cliente.com",
      nombre: "Cliente Legacy",
      empresaNombre: "Legacy SAS",
      nit: "900100100-1",
      precioSoporte: "1200000",
      fecha: "2026-02-23",
    },
  },
  {
    id: "onboard-new-annual",
    caso: 2,
    titulo: "Cliente nuevo anual contabilidad + nomina",
    descripcion: "Onboarding de empresa nueva con plan anual base.",
    camposMinimos: ["email", "nombre", "empresaNombre"],
    payloadTemplate: {
      email: "nuevo@cliente.com",
      nombre: "Cliente Nuevo",
      empresaNombre: "Nueva Empresa SAS",
      planCodigo: "PLAN-ANUAL-BASE",
      planNombre: "Plan anual base",
      valorPlan: "1800000",
      fecha: "2026-02-23",
    },
  },
  {
    id: "migrate-from-excel",
    caso: 3,
    titulo: "Migracion desde Excel",
    descripcion: "Migra items legacy a una nueva suscripcion.",
    camposMinimos: ["usuarioId", "empresaId", "planId"],
    payloadTemplate: {
      usuarioId: "REEMPLAZAR-UUID",
      empresaId: "REEMPLAZAR-UUID",
      planId: "REEMPLAZAR-UUID",
      fecha: "2026-02-23",
      items: [],
    },
  },
  {
    id: "accountant-multi-company-subscriptions",
    caso: 4,
    titulo: "Contador con tres empresas",
    descripcion: "Crea contador y suscripciones de contabilidad por empresa.",
    camposMinimos: ["email", "nombre"],
    payloadTemplate: {
      email: "contador@firma.com",
      nombre: "Contador Principal",
      fecha: "2026-02-23",
      planCodigo: "PLAN-CONTABILIDAD-MENSUAL",
      valorPlan: "120000",
      empresas: [
        { nombre: "Firma Uno" },
        { nombre: "Firma Dos" },
        { nombre: "Firma Tres" },
      ],
    },
  },
  {
    id: "renew-subscription",
    caso: 5,
    titulo: "Renovacion con precio actualizado",
    descripcion: "Renueva una suscripcion tomando el precio vigente.",
    camposMinimos: ["suscripcionId"],
    payloadTemplate: {
      suscripcionId: "REEMPLAZAR-UUID",
      fechaRenovacion: "2026-02-23",
    },
  },
  {
    id: "update-plan-prices",
    caso: 6,
    titulo: "Aumento de precios",
    descripcion: "Aplica incremento mensual y anual a un plan.",
    camposMinimos: ["planId", "incrementoMensual", "incrementoAnual"],
    payloadTemplate: {
      planId: "REEMPLAZAR-UUID",
      vigenteDesde: "2026-02-23",
      incrementoMensual: "10000",
      incrementoAnual: "100000",
    },
  },
  {
    id: "purchase-consumable",
    caso: 7,
    titulo: "Compra de consumible adicional",
    descripcion: "Compra nuevos documentos electronicos a media suscripcion.",
    camposMinimos: ["suscripcionId", "cantidad", "productoCodigo"],
    payloadTemplate: {
      suscripcionId: "REEMPLAZAR-UUID",
      productoCodigo: "DOCS-ELECTRONICOS",
      cantidad: "100",
      fecha: "2026-02-23",
    },
  },
  {
    id: "add-company-with-subscription",
    caso: 8,
    titulo: "Nueva empresa con nueva suscripcion",
    descripcion: "Agrega empresa al cliente y crea suscripcion asociada.",
    camposMinimos: ["usuarioId", "nombre", "planId"],
    payloadTemplate: {
      usuarioId: "REEMPLAZAR-UUID",
      nombre: "Empresa Nueva Cliente",
      planId: "REEMPLAZAR-UUID",
      fecha: "2026-02-23",
    },
  },
  {
    id: "upgrade-midcycle-limit",
    caso: 9,
    titulo: "Upgrade de limite con prorrateo",
    descripcion: "Incrementa limite a mitad de ciclo con ajuste prorrateado.",
    camposMinimos: ["suscripcionId", "entitlementCodigo", "nuevoLimite"],
    payloadTemplate: {
      suscripcionId: "REEMPLAZAR-UUID",
      entitlementCodigo: "LIMITE-EMPLEADOS",
      nuevoLimite: "20",
      productoId: "REEMPLAZAR-UUID",
      fecha: "2026-02-23",
    },
  },
  {
    id: "purchase-fixed-term-service",
    caso: 10,
    titulo: "Servicio de vigencia fija",
    descripcion: "Compra certificado digital sin prorrateo y con rango efectivo.",
    camposMinimos: ["suscripcionId", "productoCodigo", "fechaEfectivaInicio", "fechaEfectivaFin"],
    payloadTemplate: {
      suscripcionId: "REEMPLAZAR-UUID",
      productoCodigo: "CERTIFICADO-DIGITAL",
      fechaPago: "2026-02-23",
      fechaEfectivaInicio: "2026-03-01",
      fechaEfectivaFin: "2027-02-28",
    },
  },
];

export const WORKFLOW_MAP = new Map(WORKFLOW_CATALOG.map((w) => [w.id, w]));
