import { TableConfig } from "@/lib/repositories/crud";

const core: TableConfig[] = [
  {
    resource: "usuarios",
    tableName: "core.usuarios",
    columns: ["id", "email", "nombre", "activo", "created_at", "updated_at"],
    requiredOnCreate: ["email", "nombre"],
    idKeys: [{ name: "id", kind: "uuid" }],
  },
  {
    resource: "empresas",
    tableName: "core.empresas",
    columns: ["id", "nombre", "nit", "timezone", "activa", "created_at", "updated_at"],
    requiredOnCreate: ["nombre"],
    idKeys: [{ name: "id", kind: "uuid" }],
  },
  {
    resource: "usuarios-empresas",
    tableName: "core.usuarios_empresas",
    columns: [
      "usuario_id",
      "empresa_id",
      "rol",
      "es_principal",
      "created_at",
      "updated_at",
    ],
    requiredOnCreate: ["usuario_id", "empresa_id"],
    idKeys: [
      { name: "usuario_id", kind: "uuid" },
      { name: "empresa_id", kind: "uuid" },
    ],
  },
];

const billing: TableConfig[] = [
  {
    resource: "productos",
    tableName: "billing.productos",
    columns: [
      "id",
      "codigo",
      "nombre",
      "descripcion",
      "unidad_consumo",
      "descripcion_operativa",
      "tipo",
      "alcance",
      "es_consumible",
      "activo",
      "created_at",
      "updated_at",
    ],
    requiredOnCreate: ["codigo", "nombre", "tipo", "alcance"],
    idKeys: [{ name: "id", kind: "uuid" }],
  },
  {
    resource: "precios",
    tableName: "billing.precios",
    columns: [
      "id",
      "producto_id",
      "periodo",
      "moneda_id",
      "valor",
      "permite_prorrateo",
      "activo",
      "valido_desde",
      "valido_hasta",
      "created_at",
      "updated_at",
    ],
    requiredOnCreate: ["producto_id", "periodo", "moneda_id", "valor"],
    idKeys: [{ name: "id", kind: "uuid" }],
  },
  {
    resource: "planes",
    tableName: "billing.planes",
    columns: ["id", "codigo", "nombre", "descripcion", "pricing_mode", "periodo", "activo", "created_at", "updated_at"],
    requiredOnCreate: ["codigo", "nombre", "periodo"],
    idKeys: [{ name: "id", kind: "uuid" }],
  },
  {
    resource: "precios-planes",
    tableName: "billing.precios_planes",
    columns: [
      "id",
      "plan_id",
      "moneda_id",
      "periodo",
      "valor",
      "activo",
      "valido_desde",
      "valido_hasta",
      "created_at",
      "updated_at",
    ],
    requiredOnCreate: ["plan_id", "moneda_id", "periodo", "valor"],
    idKeys: [{ name: "id", kind: "uuid" }],
  },
  {
    resource: "items-plan",
    tableName: "billing.items_plan",
    columns: ["plan_id", "producto_id", "incluido", "cantidad"],
    requiredOnCreate: ["plan_id", "producto_id"],
    idKeys: [
      { name: "plan_id", kind: "uuid" },
      { name: "producto_id", kind: "uuid" },
    ],
  },
  {
    resource: "entitlements",
    tableName: "billing.entitlements",
    columns: ["id", "codigo", "nombre", "tipo", "alcance", "descripcion", "created_at", "updated_at"],
    requiredOnCreate: ["codigo", "nombre", "tipo", "alcance"],
    idKeys: [{ name: "id", kind: "uuid" }],
  },
  {
    resource: "entitlements-plan",
    tableName: "billing.entitlements_plan",
    columns: ["plan_id", "entitlement_id", "valor_entero", "valor_booleano"],
    requiredOnCreate: ["plan_id", "entitlement_id"],
    idKeys: [
      { name: "plan_id", kind: "uuid" },
      { name: "entitlement_id", kind: "uuid" },
    ],
  },
  {
    resource: "suscripciones",
    tableName: "billing.suscripciones",
    columns: [
      "id",
      "empresa_id",
      "plan_id",
      "precio_plan_id",
      "estado",
      "billing_cycle",
      "periodo",
      "modo_renovacion",
      "fecha_inicio",
      "periodo_actual_inicio",
      "periodo_actual_fin",
      "grace_days_granted",
      "grace_until",
      "operational_status",
      "canceled_at",
      "created_at",
      "updated_at",
    ],
    requiredOnCreate: [
      "empresa_id",
      "plan_id",
      "precio_plan_id",
      "estado",
      "billing_cycle",
      "periodo",
      "modo_renovacion",
      "fecha_inicio",
      "periodo_actual_inicio",
      "periodo_actual_fin",
    ],
    idKeys: [{ name: "id", kind: "uuid" }],
  },
  {
    resource: "politicas-cobro",
    tableName: "billing.politicas_cobro",
    columns: [
      "id",
      "scope",
      "plan_id",
      "empresa_id",
      "grace_days",
      "auto_block",
      "activo",
      "created_at",
      "updated_at",
    ],
    requiredOnCreate: ["scope"],
    idKeys: [{ name: "id", kind: "uuid" }],
  },
  {
    resource: "cobro-eventos",
    tableName: "billing.cobro_eventos",
    columns: [
      "id",
      "suscripcion_id",
      "factura_id",
      "event_type",
      "event_time",
      "actor",
      "payload_json",
      "created_at",
    ],
    requiredOnCreate: ["suscripcion_id", "event_type"],
    idKeys: [{ name: "id", kind: "uuid" }],
  },
  {
    resource: "items-suscripcion",
    tableName: "billing.items_suscripcion",
    columns: [
      "id",
      "suscripcion_id",
      "producto_id",
      "precio_id",
      "cantidad",
      "fecha_inicio",
      "fecha_fin",
      "fecha_efectiva_inicio",
      "fecha_efectiva_fin",
      "origen",
      "estado",
      "created_at",
      "updated_at",
    ],
    requiredOnCreate: ["suscripcion_id", "producto_id", "cantidad", "fecha_inicio", "origen", "estado"],
    idKeys: [{ name: "id", kind: "uuid" }],
  },
  {
    resource: "entitlements-suscripcion",
    tableName: "billing.entitlements_suscripcion",
    columns: [
      "suscripcion_id",
      "entitlement_id",
      "valor_entero",
      "valor_booleano",
      "origen",
      "efectivo_desde",
      "efectivo_hasta",
    ],
    requiredOnCreate: ["suscripcion_id", "entitlement_id", "origen", "efectivo_desde"],
    idKeys: [
      { name: "suscripcion_id", kind: "uuid" },
      { name: "entitlement_id", kind: "uuid" },
      { name: "efectivo_desde", kind: "date" },
    ],
  },
  {
    resource: "entitlements-usuario",
    tableName: "billing.entitlements_usuario",
    columns: [
      "usuario_id",
      "entitlement_id",
      "valor_entero",
      "valor_booleano",
      "efectivo_desde",
      "efectivo_hasta",
      "origen",
    ],
    requiredOnCreate: ["usuario_id", "entitlement_id", "efectivo_desde", "origen"],
    idKeys: [
      { name: "usuario_id", kind: "uuid" },
      { name: "entitlement_id", kind: "uuid" },
      { name: "efectivo_desde", kind: "date" },
    ],
  },
  {
    resource: "facturas",
    tableName: "billing.facturas",
    columns: [
      "id",
      "empresa_id",
      "suscripcion_id",
      "usuario_id",
      "fecha_emision",
      "fecha_vencimiento",
      "subtotal",
      "descuento_tipo",
      "descuento_valor",
      "descuento_monto",
      "descuento_motivo",
      "total",
      "estado",
      "metodo_pago",
      "referencia_externa",
      "notas",
      "created_at",
      "updated_at",
    ],
    requiredOnCreate: ["empresa_id", "fecha_emision", "total", "estado", "metodo_pago"],
    idKeys: [{ name: "id", kind: "uuid" }],
  },
  {
    resource: "items-factura",
    tableName: "billing.items_factura",
    columns: [
      "id",
      "factura_id",
      "producto_id",
      "precio_id",
      "descripcion",
      "cantidad",
      "precio_unitario",
      "total",
      "periodo_desde",
      "periodo_hasta",
      "created_at",
    ],
    requiredOnCreate: ["factura_id", "cantidad", "precio_unitario", "total"],
    idKeys: [{ name: "id", kind: "uuid" }],
  },
  {
    resource: "prorrateos",
    tableName: "billing.prorrateos",
    columns: [
      "id",
      "suscripcion_id",
      "producto_id",
      "desde",
      "hasta",
      "valor_original",
      "valor_prorrateado",
      "factura_id",
      "item_factura_id",
      "created_at",
    ],
    requiredOnCreate: ["suscripcion_id", "producto_id", "desde", "hasta", "valor_original", "valor_prorrateado"],
    idKeys: [{ name: "id", kind: "uuid" }],
  },
];

const all = [...core, ...billing];

export const RESOURCE_MAP = new Map<string, TableConfig>(all.map((c) => [c.resource, c]));
